run:
  timeout: 5m
  tests: false

linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocyclo
    - dupl
    - gosec
    - misspell
    - gocritic
  disable:
    - errcheck
    - goconst

linters-settings:
  gosec:
    excludes:
      - G104
  gocyclo:
    min-complexity: 30

issues:
  exclude-rules:
    - linters:
        - gosec
      text: "G104"
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
