name: 'JVS Snapshot'
description: 'Take a workspace snapshot using JVS (Juicy Versioned Workspaces)'
inputs:
  path:
    description: 'Path to snapshot (relative to repository root)'
    required: false
    default: '.'
  note:
    description: 'Snapshot note/message'
    required: false
    default: 'CI snapshot'
  tags:
    description: 'Comma-separated list of tags'
    required: false
    default: ''
  jvs-version:
    description: 'JVS version to use (default: latest)'
    required: false
    default: 'latest'
  install-only:
    description: 'Only install JVS without taking snapshot'
    required: false
    default: 'false'
outputs:
  snapshot-id:
    description: 'The created snapshot ID'
    value: ${{ steps.snapshot.outputs.id }}
  snapshot-short-id:
    description: 'The short snapshot ID (first 8 chars)'
    value: ${{ steps.snapshot.outputs.short-id }}

runs:
  using: 'composite'
  steps:
  - name: Detect JVS installation
    id: detect
    shell: bash
    run: |
      if command -v jvs &> /dev/null; then
        echo "jvs_found=true" >> $GITHUB_OUTPUT
        jvs --version
      else
        echo "jvs_found=false" >> $GITHUB_OUTPUT
      fi

  - name: Install JVS
    if: steps.detect.outputs.jvs_found != 'true'
    shell: bash
    run: |
      echo "Installing JVS ${{ inputs.jvs-version }}..."

      # Determine latest version if not specified
      VERSION="${{ inputs.jvs-version }}"
      if [ "$VERSION" = "latest" ]; then
        # Fetch latest release from GitHub API
        VERSION=$(curl -s https://api.github.com/repos/jvs-project/jvs/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
        if [ -z "$VERSION" ]; then
          echo "Warning: Could not determine latest version, using v7.0"
          VERSION="v7.0"
        fi
      fi

      echo "Using JVS version: $VERSION"

      # Download and install
      curl -LO "https://github.com/jvs-project/jvs/releases/download/$VERSION/jvs-linux-amd64"
      chmod +x jvs-linux-amd64
      sudo mv jvs-linux-amd64 /usr/local/bin/jvs

  - name: Initialize JVS repository (if needed)
    shell: bash
    run: |
      # Check if we're in a JVS repository
      if [ -d ".jvs" ]; then
        echo "Already in a JVS repository"
      else
        # Check if we can find parent JVS repo
        REPO_ROOT="$GITHUB_WORKSPACE"
        cd "$REPO_ROOT" || exit 0

        # Walk up to find .jvs directory
        while [ "$PWD" != "/" ]; do
          if [ -d ".jvs" ]; then
            echo "Found JVS repository at: $PWD"
            break
          fi
          cd ..
        done

        # If not found, create a new repository
        if [ ! -d ".jvs" ]; then
          echo "No JVS repository found, initializing..."
          cd "$REPO_ROOT"
          jvs init ci-repo
          cd "ci-repo/main"
        fi
      fi

  - name: Take snapshot
    id: snapshot
    if: inputs.install-only != 'true'
    shell: bash
    run: |
      # Parse tags
      TAGS_ARGS=()
      if [ -n "${{ inputs.tags }}" ]; then
        IFS=',' read -ra TAG_ARRAY <<< "${{ inputs.tags }}"
        for tag in "${TAG_ARRAY[@]}"; do
          TAGS_ARGS+=("--tag" "$tag")
        done
      fi

      # Set path
      SNAP_PATH="${{ inputs.path }}"
      if [ "$SNAP_PATH" = "." ]; then
        SNAP_PATH="$GITHUB_WORKSPACE"
      fi

      # Change to snapshot path
      cd "$SNAP_PATH" || { echo "Error: Path $SNAP_PATH not found"; exit 1; }

      # Find or create worktree
      if ! jvs info &> /dev/null; then
        echo "Not in a JVS worktree, initializing..."
        # This is handled by the init step above
      fi

      # Take snapshot
      echo "Taking snapshot of: $SNAP_PATH"
      echo "Note: ${{ inputs.note }}"

      OUTPUT=$(jvs snapshot "${{ inputs.note }}" "${TAGS_ARGS[@]}" --json)

      # Extract snapshot ID
      SNAPSHOT_ID=$(echo "$OUTPUT" | grep -o '"snapshot_id":"[^"]*"' | cut -d'"' -f4)
      SHORT_ID=$(echo "$SNAPSHOT_ID" | cut -c1-8)

      echo "Snapshot created: $SNAPSHOT_ID"
      echo "id=$SNAPSHOT_ID" >> $GITHUB_OUTPUT
      echo "short-id=$SHORT_ID" >> $GITHUB_OUTPUT

      # Set output for GitHub Actions
      {
        echo "id=$SNAPSHOT_ID"
        echo "short-id=$SHORT_ID"
      } >> $GITHUB_OUTPUT

  - name: Summary
    if: inputs.install-only != 'true'
    shell: bash
    run: |
      echo "### 📸 JVS Snapshot Summary" >> $GITHUB_STEP_SUMMARY
      echo "" >> $GITHUB_STEP_SUMMARY
      echo "- **Snapshot ID:** \`${{ steps.snapshot.outputs.id }}\`" >> $GITHUB_STEP_SUMMARY
      echo "- **Short ID:** \`${{ steps.snapshot.outputs.short-id }}\`" >> $GITHUB_STEP_SUMMARY
      echo "- **Note:** ${{ inputs.note }}" >> $GITHUB_STEP_SUMMARY
      if [ -n "${{ inputs.tags }}" ]; then
        echo "- **Tags:** ${{ inputs.tags }}" >> $GITHUB_STEP_SUMMARY
      fi
      echo "" >> $GITHUB_STEP_SUMMARY
      echo "To restore this snapshot:" >> $GITHUB_STEP_SUMMARY
      echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
      echo "jvs restore ${{ steps.snapshot.outputs.short-id }}" >> $GITHUB_STEP_SUMMARY
      echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
